export const studentSelect = {
  studentId: true,
  name: true,
  email: true,
  batch: true,
  session: true,
  department: true,
  role: true,
  profileImage: true,
  createdAt: true,
  updatedAt: true,
}
export const teacherSelect = {
  teacherId: true,
  name: true,
  email: true,
  department: true,
  role: true,
  designation: true,
  specialization: true,
  profileImage: true,
  deptHead: true,
  createdAt: true,
  updatedAt: true,
}
